Template.editRecurring.events
  'click .pause_plan': (event) ->
    id = event.currentTarget.id
    Meteor.call 'updateTithePlanStatus', id, 'paused'
    return
  'click .start_plan': (event) ->
    id = event.currentTarget.id
    Meteor.call 'updateTithePlanStatus', id, 'active'
    return
  'click .edit': ->
    $('.PlanView').hide()
    $('.PlanEdit').show()
    return
  'click .cancel_edit': ->
    $('.PlanView').show()
    $('.PlanEdit').hide()
    return
  'click .save_edit': (event, template) ->
    amt = $('#amount').val()
    recur = $('#repeat_type').val()
    if amt >= 5 and recur != ''
      Meteor.call 'updateTithePlan', id, amt, recur, (err, result) ->
        if result
          $('.PlanView').show()
          $('.PlanEdit').hide()
        return
    else
      alert 'You must fill out all fields'
    return
  'click .delete': (event, template) ->
    Meteor.call 'updateTithePlanStatus', template.data.plan._id, 'canceled', (err, result) ->
      if result
        Router.go '/recurring'
      return
    return
Template.editRecurring.helpers
  'noLink': ->
    true
  'card_details': ->
    `var card`
    `var card`
    lastCharge = Tithes.findOne(@plan.lastCharge)
    card = lastCharge.data.source
    card = MyCards.findOne(cardid: card)
    if card
      card.brand + ' ending in ' + card.last4 + ' (exp. ' + card.exp_month + '/' + card.exp_year + ')'
    else
      card = MyCards.findOne('default': true)
      card.brand + ' ending in ' + card.last4 + ' (exp. ' + card.exp_month + '/' + card.exp_year + ')'
  'newRecurrence': ->
    if @plan.recurrence == 'bi-weekly'
      'every other week'
    else
      @plan.recurrence
  'recurSelect': ->
    monthly = ''
    bi = ''
    weekly = ''
    daily = ''
    switch @plan.recurrence
      when 'monthly'
        monthly = ' selected '
      when 'bi-weekly'
        bi = ' selected '
      when 'weekly'
        weekly = ' selected '
      when 'daily'
        daily = ' selected '
    html = '<select name=\'repeat_type\' id=\'repeat_type\' class=\'form-control\'>'
    html += '<option><i>select an option</i></option>'
    html += '<option value=\'monthly\'' + monthly + '>every month</option>'
    html += '<option value=\'bi-weekly\'' + bi + '>every two weeks</option>'
    html += '<option value=\'weekly\'' + weekly + '>every week</option>'
    html += '<option value=\'daily\'' + daily + '>every day</option></select>'
    html
  'newAmount': ->
    numeral(@plan.amount).format '$0,0.00'
  'flatAmount': ->
    numeral(@plan.amount).format '0,0'
  'churchName': ->
    Meteor.subscribe 'churchById', @plan.church
    church = Meteor.users.findOne(@plan.church)
    church.profile.churchName + ' - ' + church.profile.address.city
  'action': ->
    `var data`
    if @plan.status == 'active'
      data =
        title: 'Pause'
        style: 'success'
        class: 'pause_plan'
      data
    else
      data =
        title: 'Restart'
        style: 'danger'
        class: 'start_plan'
      data
Template.editRecurring.onRendered ->
  $('#editRecurringDT').dataTable()
  return

# ---
# generated by js2coffee 2.2.0