Template.titheDetail.helpers
  'newDate': ->
    moment.unix(@date).format 'MM/DD/YYYY, h:mm a'
  'newAmount': ->
    numeral(@amount / 100).format '$0,0.00'
  'churchName': ->
    Meteor.subscribe 'churchById', @church
    church = Meteor.users.findOne(@church)
    try
      return if church.profile.churchName then church.profile.churchName + ' - ' + church.profile.address.city else 'Anonymous'
    catch err
      return 'Anonymous'
    return
  'userName': ->
    Meteor.subscribe 'userById', @userID
    userDet = Meteor.users.findOne(@userID)
    try
      return if userDet.profile.name then userDet.profile.name else 'Anonymous'
    catch err
      return 'Anonymous'
    return
Template.titheDetailWell.helpers
  'newDate': ->
    moment.unix(@date).format 'MM/DD/YYYY, h:mm a'
  'newAmount': ->
    numeral(@amount / 100).format '$0,0.00'
  'churchName': ->
    Meteor.subscribe 'churchById', @church
    church = Meteor.users.findOne(@church)
    church.profile.churchName + ' - ' + church.profile.address.city
Template.user_tithes.onRendered ->
  $('#user_tithesDatatable').dataTable
    dom: '<\'row\'<\'col-sm-4\'l><\'col-sm-4 text-center\'B><\'col-sm-4\'f>>tp'
    'lengthMenu': [
      [
        10
        25
        50
        -1
      ]
      [
        10
        25
        50
        'All'
      ]
    ]
    buttons: [
      {
        extend: 'copy'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'csv'
        title: 'ExampleFile'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'pdf'
        title: 'ExampleFile'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'print'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
    ]
  return
Template.churchTithes.onRendered ->
  $('#giftsChurchDatatable').dataTable
    dom: '<\'row\'<\'col-sm-4\'l><\'col-sm-4 text-center\'B><\'col-sm-4\'f>>tp'
    'lengthMenu': [
      [
        10
        25
        50
        -1
      ]
      [
        10
        25
        50
        'All'
      ]
    ]
    buttons: [
      {
        extend: 'copy'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'csv'
        title: 'ExampleFile'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'pdf'
        title: 'ExampleFile'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
      {
        extend: 'print'
        className: 'btn-sm'
        exportOptions: columns: [
          0
          1
          2
          3
        ]
      }
    ]
  return
Template.titheDetail.events 'click #giveVerification': (e, t) ->
  e.preventDefault()
  titheId = @_id
  bootbox.confirm
    message: 'Are you sure to confirm verification of give?'
    buttons:
      confirm:
        label: 'Yes'
        className: 'btn-success'
      cancel:
        label: 'No'
        className: 'btn-danger'
    callback: (result) ->
      if result
        Meteor.call 'giveVerificationMethod', titheId, (err, res) ->
          if err
            alert err.reason, ''
          else
            alert 'Give is verified By you', 'Verified'
          return
      return
  return

# ---
# generated by js2coffee 2.2.0